import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("about", "routes/about.tsx"),
  route("for-authors", "routes/for-authors.tsx"),
  route("works", "routes/works.tsx"),
  route("works/:workSlug", "routes/work.tsx"),
  route("works/:workId/engagement", "routes/work-engagement.tsx"),
  route("works/:workSlug/chapters/:chapterId", "routes/chapter.tsx"),
  route("users/:username", "routes/public-profile.tsx"),
  route("tags/search", "routes/public-tag-search.ts"),
  route("tags/:tagSlug", "routes/tag.tsx"),
  route("messages/:username", "routes/messages.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("logout", "routes/logout.tsx"),
  route("profile", "routes/profile.tsx"),
  route("notifications", "routes/notifications.tsx"),
  route("events", "routes/events.ts"),
  route("analytics/track", "routes/analytics-track.ts"),
  route("analytics", "routes/analytics.tsx"),
  route("analytics/works/:workId", "routes/analytics-work.tsx"),
  route("analytics/works/:workId/chapters/:chapterId", "routes/analytics-chapter.tsx"),
  route("admin/users", "routes/admin-users.tsx"),
  route("admin/tags", "routes/admin-tags.tsx"),
  route("editor", "routes/editor.tsx"),
  route("editor/works/:workId", "routes/admin-chapters.tsx"),
  route("editor/works/:workId/tags/search", "routes/tag-search.ts"),
  route("editor/works/:workId/chapters/:chapterId", "routes/admin-chapter.tsx"),
] satisfies RouteConfig;
